[project]
name = "sugar-fight"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "gymnasium==1.1.1",
    "ray[rllib]>=2.49.2",
    "stable-baselines3[extra]>=2.7.0",
]
